package com.risk.network;

/**
 * This enum is used to store the different types of messages that can be sent between the client
 * and the server.
 *
 * @author floribau
 */
public enum MessageType {
  TRADE_CARDS_REQUEST,
  TRADE_CARDS_MESSAGE,
  ATTACK_MOVE_REQUEST,
  ATTACK_MOVE_MESSAGE,
  DISTRIBUTION_REQUEST,
  DISTRIBUTION_MESSAGE,
  DISCONNECT_MESSAGE,
  HEART_BEAT_MESSAGE,
  MOVE_TROOPS_REQUEST,
  MOVE_TROOPS_MESSAGE,
  PLACE_TROOPS_REQUEST,
  PLACE_TROOPS_MESSAGE,
  UPDATED_GAME_STATE_MESSAGE,
  GAME_STATE_RECEIVED_MESSAGE,
  CHAT_MESSAGE,
  WELCOME_MESSAGE,
  UPDATE_PLAYERS_LOBBY_MESSAGE,
  PLAYER_READY_MESSAGE,
  PLAYERS_READY_UPDATE_MESSAGE,
  USER_INFO_MESSAGE,
  START_GAME_MESSAGE,
  PLAYER_ADDED_TO_CLIENT_MESSAGE,
  GAME_CONTROLLER_ADDED_TO_PLAYER_MESSAGE,
  DICE_RESULT_DETERMINE_BEGINNER_MESSAGE,
  PRESSED_CONTINUE_AFTER_DETERMINE_BEGINNER_MESSAGE,
  SET_AI_PLAYER_ON_READY_MESSAGE,
  TEST_MESSAGE,
  NEXT_PHASE_MESSAGE,
  NEXT_PHASE_REQUEST,
  GAME_OVER_MESSAGE,
  SERVER_SHUTDOWN_MESSAGE
}